### ISSUE TITLE
Build in linux distribution

### ISSUE THREAD

**Issue by eliot4321** [martindisch/oscore#2] opened 2020-05-05 08:32 UTC
Hi,

It's  possible to try this library in a linux distribution (Ubuntu)?

thanks

**Comment by martindisch** [comment] 2020-05-05 17:42
Absolutely, since it's written in Rust it runs on [all platforms supported by the compiler](https://forge.rust-lang.org/release/platform-support.html), so pretty much everything from microcontrollers to supercomputers. In terms of OS, you can easily compile it on Linux, Windows and OSX.

I'm not sure if it's what you're looking for, but one of my repositories has a [desktop client](https://github.com/martindisch/oscore-demo/tree/master/desktop-client) as an examle of how it's used.

**Comment by eliot4321** [comment] 2020-05-05 20:13
Hi @martindisch ,
 
Thank you for your answer.
I would like to create a simple setup between an OSCORE client and OSCORE server where they exchange keys using EDHOC and the OSCORE client sends a HelloMessage to the OSCORE server.
I have checked the desktop-client as you suggested and it seems to compile and run properly.  I have tried to build the server from the oscore-demo repository but I can't build it in my Ubuntu machine. I get the following error:
 
A plugin/crate was declared but cannot be found.
 
can't find crate for `core`
  |
  = note: the `thumbv7em-none-eabihf` target may not be installed
 
Do you know why it can't find this plugin?
And, do you know if my setup is possible to run with the desktop-client and the server?
 
Thank you very much!

**Comment by martindisch** [comment] 2020-05-05 20:30
The problem is that this demo runs on embedded devices (see the `.cargo/config` and `build.rs` files as well as the dependencies in `Cargo.toml`). Both the `client` and `server` crates are for STM32 microcontrollers, hence the ARM target. The setup is explained in the [readme](https://github.com/martindisch/oscore-demo/blob/master/README.md). For the client there is a desktop version (the `desktop-client` you managed to compile), but not for the server.

You can either try to take all the EDHOC and OSCORE stuff that is not device-specific from the server and move it into a new crate, or you can build your server from scratch by looking at the [examples](https://github.com/martindisch/oscore/tree/master/examples) for usage of the EDHOC and OSCORE parts of the library and implementing the server functionality yourself.

**Comment by eliot4321** [comment] 2020-05-06 16:16
Hi,

we have tried, but we are not familiar with RUST language.
Could you please create  HelloworldServer for ubuntu, so we can base on it as starting point?

Thanks in advance.

**Comment by martindisch** [comment] 2020-05-06 17:53
Since it's not too much trouble, I went ahead and did just that. There is now a [desktop-server](https://github.com/martindisch/oscore-demo/tree/master/desktop-server) in the demo repo. Once you've compiled both `desktop-server` and `desktop-client` (ideally on two different machines in your local network), you can go ahead and start the server on one, then the client on the other. They will do the EDHOC exchange and afterwards the client will start sending alternating requests. One is to the `/hello` endpoint of the server, which will just return a "Hello, world!" message. The other is to the `/echo` endpoint, which will return whatever it is sent. The client will send messages of the form "Iteration N" where N is the number of the current request. This exchange will continue until you stop it. You can actually have an arbitrary number of clients, but I'm assuming in my example that you have a server at 192.168.0.101 and the client on 192.168.0.102

On the server:
```console
[user@server ~]$ ./desktop-server -p 5683

Rx(65)
IP packet from 192.168.0.102
Received an EDHOC message while waiting for message_1
Successfully built message_2
Responding with CoAP packet
Tx(123)

Rx(107)
IP packet from 192.168.0.102
Received an EDHOC message while waiting for message_3
Successfully derived the master secret and salt
[9, 2, 157, 176, 12, 62, 1, 39, 66, 195, 168, 105, 4, 7, 76, 14]
[129, 2, 151, 34, 162, 48, 74, 6]
Responding with CoAP packet
Tx(8)

Rx(28)
IP packet from 192.168.0.102
Unprotecting OSCORE request
Request for the /hello resource
Protecting OSCORE response
Responding with CoAP packet
Tx(33)

Rx(39)
IP packet from 192.168.0.102
Unprotecting OSCORE request
Request for the /echo resource
Protecting OSCORE response
Responding with CoAP packet
Tx(31)

Rx(28)
IP packet from 192.168.0.102
Unprotecting OSCORE request
Request for the /hello resource
Protecting OSCORE response
Responding with CoAP packet
Tx(33)
```

On the client:
```console
[user@client ~]$ ./desktop-client -p 5683 192.168.0.101:5683
Sent message_1 to peer and received message_2
Successfully derived the master secret and salt
[9, 2, 157, 176, 12, 62, 1, 39, 66, 195, 168, 105, 4, 7, 76, 14]
[129, 2, 151, 34, 162, 48, 74, 6]
Sent message_3 to peer
Got response: Hello, world!
Got response: Iteration 1
Got response: Hello, world!
```

I would like to point out that the demo client and server use hardcoded keys (from the test vectors of the RFC), which is totally insecure. These would need to be randomly generated in a real deployment. And my implementation is purely for research purposes, not audited and should therefore not be used in any production environment. Especially since EDHOC is still a draft and not a finished RFC.

Since I'm interested, could you tell me a little more about what you plan on using this for?

**Comment by onovo1** [comment] 2020-05-07 05:40
@martindisch Thank you very much for your help! These is awesome!

Regarding your question, we (eliot4321 and I) are interested to check the performance of EDHOC to verify that it is as good as they claim. Yours is the only implementation of EDHOC as far as we know. So, congratulations on this! :+1: 

By the way, there is an error that I can't figure out how to solve it. I think it is a beginners errors but I am not that familiar with Rust. When I clone your repository and compile the desktop-server, the server compiles fine. However, if I only clone the desktop-server and the desktop-client and I compile both, the desktop-server gives me the following error in Ubuntu:

```
error[E0463]: can't find crate for `std`
  |
  = note: the `thumbv7em-none-eabihf` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: could not compile `rand_core`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed

```
Do you know why is that? Is there a reason the rest of the files are needed for compilation? Thank you for your help again!

**Comment by martindisch** [comment] 2020-05-07 16:39
It's nice to see people interested in EDHOC, sounds like a cool project!

I'm assuming you're referring to [your repo](https://github.com/onovo1/oscore-edhoc-demo) when you describe the problem. The reason for your issue is that you seem to have copied in the `.cargo` directory with the `.cargo/config` file from the embedded server. This configuration file tells the compiler to build against the specific ARM CPU architecture in use on the embedded devices. You don't have this target installed, which is why you get this error message. Just remove the `.config` directory, since you want to compile for x86_64 anyway.

By the way, when you use code from another open source project, you should abide by its license. You can do that by creating a file in your repository where you put the license notices of all projects your code makes use of. In your case that's only my demo, so I suggest creating a file `LICENSE-3RD-PARTY` and pasting the contents of this [copyright notice](https://github.com/martindisch/oscore-demo/blob/master/LICENSE-MIT) from my demo.
Once that's done, it would be nice (although you are not legally required to do so) if you would license your copy as well, so that other people can work with it. If you don't put a `LICENSE` file or similar in your project, exclusive copyright applies. This means that even though the code is publicly shared on GitHub, nobody is allowed to use it ([more information](https://choosealicense.com/no-permission/)). To enable other people to benefit from your work, create a `LICENSE` file and put a common open source license in there. For your project, the [MIT license](https://choosealicense.com/licenses/mit/) might be appropriate (same one I'm using for my demo). You can copy that, put in the current year and your name and that's it.

**Comment by onovo1** [comment] 2020-05-07 18:35
Hi @martindisch 

Thank you for your answer. Yes, I was referring to the public repo in my account. I created it yesterday just for testing and playing a bit with your code. I was planning to delete that repo and fork your repository. Even though I kept your name in my copy, I think it would be fair to fork it. Then, people can check your code if they are interested about the rest of your code. Besides, that code is yours and you should have all the credit. 

Ah, now the code compiles too. :dancing_men: 
I will keep your license terms in the forking as you recommend.

**Comment by martindisch** [comment] 2020-05-07 18:50
Ah, never mind then, if you fork it you're fine and don't have to do anything else. But if you make any substantial changes, do feel free to move my license notice into `LICENSE-3RD-PARTY` and put your own into the `LICENSE` file. After all, your changes are your own and the repository can reflect your authorship.

Since you're looking into the performance of EDHOC, maybe some of the work I did can help you. For my thesis, I did benchmarks of my implementation on desktop and embedded systems. I'm including the [part about EDHOC](https://github.com/martindisch/oscore/files/4595074/excerpt.pdf) here in case these numbers are useful to you.

**Comment by onovo1** [comment] 2020-05-07 19:05
OK, I [have forked](https://github.com/onovo1/oscore-demo) your repo and deleted the other repository. It is better that way. I have kept the licenses too. 

Thank you for sharing your benchmarks. They look very promising! BTW, I think your CoAP implementation is not implementing the CoAP timers, right? In other words, can the CoAP requests timeout?

**Comment by martindisch** [comment] 2020-05-07 19:41
That is correct. When I started my project, there weren't any CoAP crates in Rust for embedded systems. [coap-rs](https://github.com/covertness/coap-rs) is a good one, but it does too many things (implements full server and client) and therefore isn't suitable for embedded. To get the minimal CoAP message manipulation functionality that OSCORE needs, I had to take the relevant parts of coap-rs and put them into a [new crate](https://github.com/martindisch/coap-lite) that can function in an embedded context. It doesn't do anything fancy though, it's sole purpose is to parse and build CoAP packets, which is all my EDHOC/OSCORE library needs. The library is pretty low-level and I/O-free, meaning it doesn't implement a CoAP server, that is the user's responsibility. The client and server in the demo repository do just that, they are essentially self-made, bare-bones CoAP client and server. Of course they are nowhere near being standards-compliant, it's just a demo after all.

I was time-constrained in my project, so you shouldn't expect too much. For EDHOC I only implemented one of three authentication mechanisms and OSCORE is also lacking in security context derivation mechanisms and some optional features like Observe or block-wise transfer. As I said, it's a purely academic implementation and not intended for real-world deployments.

**Comment by onovo1** [comment] 2020-05-07 20:34
I see, thank you for the explanation. 
Yeah, time is always an issue in the projects. :/ However, as you said, your implementation is good enough for testing purposes.

I might look into integrating in your code the whole coap-rs library then. That might make sense for the desktop clients since they are not as constrained as the embedded devices. Do you think that integration will be difficult to do?
You mentioned that the EDHOC library is only implementing one authentication method, is that the Raw Public Keys (RPK) method?

**Comment by martindisch** [comment] 2020-05-08 16:43
It depends on what you need. Keep in mind that EDHOC itself is completely unrelated to CoAP. It can be transported in CoAP messages, but is transport-agnostic. So if you only want to test EDHOC but for some reason have to do it in a setup with full CoAP functionality, then the best approach would be to use coap-rs to build your full CoAP server that exposes an endpoint like `/.well-known/edhoc` and then use the EDHOC part of [my library](https://github.com/martindisch/oscore) to implement the handling of EDHOC messages.
OSCORE is more difficult, as it's pretty tightly coupled to CoAP, because it needs to work directly on CoAP packets to protect/unwrap them.
I don't know your specific requirements, but I'm thinking you might not even need a full CoAP setup. You can easily compare key exchange mechanisms like EDHOC by looking at the message sizes  (that's directly correlated to the networking and a significant portion of the energy costs associated with them) and the processing costs (either reason about the cryptographic primitives and other computational steps or directly benchmark or measure CPU cycles spent). There's no need to pull in the whole network stack, because then you end up measuring that instead. Unless of course that's the goal.

And yes, my EDHOC implements the RPK method, but does not support the unprotected and protected opaque application data (`UAD_1`, `UAD_2`, `PAD_3`). Although that shouldn't be an issue.

**Comment by onovo1** [comment] 2020-05-10 20:11
OK, I thought it would be as simple as replacing the coap-lite library for the coap-rs library but it is not. After checking your code, I realized that there is much more work involve apparently.
Somehow, we were interested to test the full protocol stack (CoAP + OSCORE + EDHOC), not only the key management part. 

When you talk about UAD and PAD, are you referring to the 'Auxiliary Data'?

**Comment by martindisch** [comment] 2020-05-11 18:15
I haven't seen it called this way, but you could say that it's auxiliary data. The draft puts it this way:
```
   EDHOC allows opaque application data (UAD and PAD) to be sent in the
   EDHOC messages.  Unprotected Application Data (UAD_1, UAD_2) may be
   sent in message_1 and message_2 and can be e.g. be used to transfer
   access tokens that are protected outside of EDHOC.  Protected
   application data (PAD_3) may be used to transfer any application data
   in message_3.
```

**Comment by onovo1** [comment] 2020-05-11 18:48
Aha, right. The last version of the draft has changed that terminology. That's why the confusion. 

In the new version, it is referred as auxiliary data:
https://tools.ietf.org/html/draft-selander-lake-edhoc-01#section-3.6

**Comment by martindisch** [comment] 2020-05-11 19:50
That makes sense, they seem to have moved the draft now that they're about to enter the final phase. That's another thing to keep in mind, my implementation is based on version 14.

I'm going to close this issue for now, if there are any interesting developments in your work, feel free to let me know.

**Closed as completed by martindisch** 2020-05-11 19:50 UTC

**Comment by onovo1** [comment] 2020-05-11 20:22
thank you for your help, @martindisch
